name: Auto Format HTML

on:
  push:

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.4.0

      - name: Setup Node.js
        uses: actions/setup-node@v6.4.0
        with:
          node-version: "20"

      - name: Format HTML
        run: npx prettier@3 --write --parser html -- '**/*.html'

      - name: Verify HTML formatting
        run: npx prettier@3 --check --parser html -- '**/*.html'

      - name: Commit formatting changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Apply automatic HTML formatting fixes"
